### PR TITLE
Update Data_Types.py

### PR DESCRIPTION
**Pull request by theanujsinha01**

### CODE REVIEW

**Comment by theanujsinha01** [comment]
commit change

**Comment by theanujsinha01** [comment]
commit change

**Comment by theanujsinha01** [comment]
change

**Review by theanujsinha01 — COMMENTED** [review]
changed

**Comment by thepankajsinha** [comment]
changed

**Review by thepankajsinha — COMMENTED** [review]
changed

**Review by thepankajsinha — COMMENTED** [review]
ok

**Pull request closed without merging**
